# Generated by Django 5.2.12 on 2026-08-29 09:00

from datetime import time

import django.db.models.deletion
from django.db import migrations, models


def seed_master_services_and_schedules(apps, schema_editor):
    Master = apps.get_model("core", "Master")
    Service = apps.get_model("core", "Service")
    WorkSchedule = apps.get_model("core", "WorkSchedule")

    services = list(Service.objects.filter(is_active=True))
    for master in Master.objects.filter(is_active=True):
        if services:
            master.services.add(*services)

        for weekday in range(5):
            WorkSchedule.objects.get_or_create(
                master=master,
                weekday=weekday,
                start_time=time(9, 0),
                end_time=time(21, 0),
            )
        for weekday in (5, 6):
            WorkSchedule.objects.get_or_create(
                master=master,
                weekday=weekday,
                start_time=time(10, 0),
                end_time=time(18, 0),
            )


def clear_seeded_schedules(apps, schema_editor):
    WorkSchedule = apps.get_model("core", "WorkSchedule")
    WorkSchedule.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_client_appointment_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="masters",
                to="core.service",
                verbose_name="Услуги",
            ),
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Начало работы")),
                ("end_time", models.TimeField(verbose_name="Окончание работы")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedules",
                        to="core.master",
                        verbose_name="Мастер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочее время",
                "verbose_name_plural": "Рабочее время",
                "ordering": ["master", "weekday", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("master", "weekday", "start_time", "end_time"),
                        name="unique_master_work_interval",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("start_time__lt", models.F("end_time"))),
                        name="work_schedule_start_before_end",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            seed_master_services_and_schedules,
            clear_seeded_schedules,
        ),
    ]
